openapi: 3.0.0
info:
  title: Rest API - SIG-SEG
  description: Sistema de gerenciamento e cadastro de denúncias e ocorrências
  version: 1.0.0

paths:
  auth/signup:
    post:
      summary: Cadastro de usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                name:
                  type: string
      responses:
        "200":
          description: Usuário cadastrado com sucesso
  
  auth/login:
    post:
      summary: Autenticação do usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Login bem-sucedido, retorna usuário e token

  /dashboard:
    get:
      summary: Obtém dados do dashboard
      responses:
        "200":
          description: Retorna contagem de denúncias e ocorrências

  /occurrence:
    post:
      summary: Criar uma nova ocorrência
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                reportId:
                  type: integer
                userId:
                  type: integer
      responses:
        "201":
          description: Ocorrência criada com sucesso

  /occurrence/{id}:
    delete:
      summary: Deletar uma ocorrência
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Ocorrência deletada com sucesso

    put:
      summary: Atualizar uma ocorrência
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                description:
                  type: string
                status:
                  type: string
                userId:
                  type: integer
                reportId:
                  type: integer
                title:
                  type: string
      responses:
        "200":
          description: Ocorrência atualizada com sucesso

  /occurrences:
    get:
      summary: Listar todas as ocorrências
      parameters:
        - name: description
          in: query
          schema:
            type: string
        - name: status
          in: query
          schema:
            type: string
        - name: reportId
          in: query
          schema:
            type: integer
        - name: userId
          in: query
          schema:
            type: integer
        - name: title
          in: query
          schema:
            type: string
      responses:
        "200":
          description: Lista todas as ocorrências

  /occurrences/public:
    get:
      summary: Listar todas as ocorrências enviando somente dados públicos
      parameters:
        - name: description
          in: query
          schema:
            type: string
        - name: status
          in: query
          schema:
            type: string
        - name: title
          in: query
          schema:
            type: string
      responses:
        "200":
          description: Lista de ocorrências enviando somente os dados públicos
  /report:
    post:
      summary: Criar uma nova denúncia
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                addressReport:
                  type: string
                cityReport:
                  type: string
                UFReport:
                  type: string
                countryReport:
                  type: string
                status:
                  type: string
                reporterName:
                  type: string
                userId:
                  type: integer
                CPF:
                  type: string
                telephone:
                  type: string
                email:
                  type: string
                titleReport:
                  type: string
      responses:
        "201":
          description: Denúncia criada com sucesso

  /report/{id}:
    put:
      summary: Atualizar uma denúncia
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                addressReport:
                  type: string
                cityReport:
                  type: string
                UFReport:
                  type: string
                countryReport:
                  type: string
                status:
                  type: string
                reporterName:
                  type: string
                userId:
                  type: integer
                CPF:
                  type: string
                telephone:
                  type: string
                email:
                  type: string
                titleReport:
                  type: string
      responses:
        "200":
          description: Denúncia atualizada com sucesso

    delete:
      summary: Deletar uma denúncia
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Denúncia deletada com sucesso

  /report/simple:
    get:
      summary: Listar somente as denúncias que não estão em nunhuma ocorrência, retornando apenas o id e o título
      responses:
        "200":
          description: Lista de denúncias públicas
  /report/complet:
    get:
      summary: Listar todas as denúncias retornando apenas o id e o título
      responses:
        "200":
          description: Lista de denúncias públicas

  /report/{code}:
    get:
      summary: Buscar denúncia pelo código para usuários públicos
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Retorna a denúncia correspondente ao código fornecido

  /reports:
    get:
      summary: Listar todas as denúncias
      parameters:
        - name: description
          in: query
          schema:
            type: string
        - name: status
          in: query
          schema:
            type: string
        - name: reporterName
          in: query
          schema:
            type: string
        - name: CPF
          in: query
          schema:
            type: string
        - name: addressReport
          in: query
          schema:
            type: string
        - name: cityReport
          in: query
          schema:
            type: string
        - name: UFReport
          in: query
          schema:
            type: string
        - name: countryReport
          in: query
          schema:
            type: string
        - name: titleReport
          in: query
          schema:
            type: string
      responses:
        "200":
          description: Lista de todas as denúncias